# Generated by Django 4.0.4 on 2022-05-16 00:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0008_auto_20210118_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestFriendship',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Friends',
            field=models.ManyToManyField(related_name='FriendUser', through='drf_user.Friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='Requests',
            field=models.ManyToManyField(related_name='RequestToUser', through='drf_user.RequestFriendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authtransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='requestfriendship',
            name='Receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toRequestUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestfriendship',
            name='Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofRequestUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IdentifierNumber', models.IntegerField()),
                ('Content', models.CharField(max_length=4096)),
                ('Type', models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video')], default='Text', max_length=5)),
                ('Date', models.DateTimeField(default=datetime.datetime(2022, 5, 16, 0, 55, 9, 850911, tzinfo=utc))),
                ('Receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toMessageUser', to=settings.AUTH_USER_MODEL)),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ofMessageUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friendship',
            name='Person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofFriendUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='Person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toFriendUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='Messages',
            field=models.ManyToManyField(related_name='MessageUser', to='drf_user.message'),
        ),
        migrations.AlterUniqueTogether(
            name='requestfriendship',
            unique_together={('Receiver', 'Sender')},
        ),
    ]
