# Generated by Django 4.0.4 on 2022-05-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0009_friendship_requestfriendship_user_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
